trigger:
  branches:
    include:
      - main  # or the branch you want to monitor

variables:
  imageName: 'your-app'
  imageTag: 'latest'
  localServer: '20.151.74.48'  # Replace with your local server IP
  sshUser: 'azuser'  # Replace with your SSH username
  sshKey: '$(sshKey)'  # SSH private key as a pipeline variable or Azure DevOps secret
  dockerfilePath: 'Dockerfile'

jobs:
- job: Deploy
  pool:
    vmImage: 'ubuntu-latest'  # Use an Azure-hosted agent with SSH capabilities
  steps:
  - task: Checkout@1
    inputs:
      repository: 'self'
      clean: true

  - script: |
      tar -czf source-code.tar.gz .
    displayName: 'Package source code'

  - script: |
      scp -i $(sshKey) source-code.tar.gz $(sshUser)@$(localServer):/tmp/
    displayName: 'Transfer source code to local server'

  - script: |
      ssh -i $(sshKey) $(sshUser)@$(localServer) << 'EOF'
        cd /tmp
        tar -xzf source-code.tar.gz
        cd your-app-directory  # Replace with the directory where the Dockerfile is located
        docker build -t $(imageName):$(imageTag) -f $(dockerfilePath) .
        docker run -d -p 80:80 $(imageName):$(imageTag)
      EOF
    displayName: 'Build and deploy Docker image on local server'
