trigger:
  branches:
    include:
      - main  # or the branch you want to monitor

variables:
  imageName: 'your-react-app'
  imageTag: 'latest'
  localServer: '20.151.74.48'
  sshUser: 'azuser'

pool:
  name: 'Default'  # Specify the named pool

jobs:
- job: Build
  steps:
  - task: Checkout@1
    inputs:
      repository: 'self'
      clean: true

  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies and build React app'

  - task: Docker@2
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: '$(imageName):$(imageTag)'
      buildContext: '.'
    displayName: 'Build Docker image'

  - script: |
      docker save $(imageName):$(imageTag) | gzip > $(Build.ArtifactStagingDirectory)/$(imageName).tar.gz
    displayName: 'Save Docker image to file'

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: docker-image
    displayName: 'Publish Docker image artifact'

- job: Deploy
  dependsOn: Build
  steps:
  - download: current
    artifact: docker-image
    displayName: 'Download Docker image artifact'

  - script: |
      scp $(Pipeline.Workspace)/docker-image/$(imageName).tar.gz $(sshUser)@$(localServer):/tmp/
    displayName: 'Transfer Docker image to local server'

  - script: |
      ssh $(sshUser)@$(localServer) "docker load < /tmp/$(imageName).tar.gz && docker run -d -p 80:80 $(imageName):$(imageTag)"
    displayName: 'Deploy Docker image on local server'
